### ISSUE TITLE
Display logo and information side by side

### ISSUE THREAD

**Issue by toddmcintire** [toddmcintire/jsfetch#20]
Currently the logo is displayed on top of everything else, it should be displayed side by side.
The logo should be on the left and the information on the right.

**Comment by adrianmarinwork** [comment]
Hello hello, I can take care of this if you want.

**Comment by toddmcintire** [comment]
> Hello hello, I can take care of this if you want.

please do! 😃

**Comment by adrianmarinwork** [comment]
What do you think? Do you like it like this?
![image](https://user-images.githubusercontent.com/118568289/204393622-159c4774-3537-4fbe-aa20-3f12f0d29303.png)

**Comment by toddmcintire** [comment]
Looks perfect! 👍

**Comment by JenieX** [comment]
Wouldn't it get messed up and look bad if the width of the terminal is smaller?

**Comment by toddmcintire** [comment]
I think it may, but I think we could solve it in the long run. 

If we can detect the terminals size somehow we could display different sized logos.

**Comment by JenieX** [comment]
> If we can detect the terminals size somehow we could display different sized logos.

Would be cool if that is possible.
