### ISSUE TITLE
Return resolution for Linux based systems.

### ISSUE THREAD

**Issue by toddmcintire** [toddmcintire/jsfetch#21]
The function ```getResolution()``` currently only returns the resolutions for darwin and windows based systems, please create a statement for linux based systems.

**Comment by bleakprestiger** [comment]
Hi @toddmcintire, can you please assign this issue to me. I am interested to work on this issue.

**Comment by gokul-srinath** [comment]
@toddmcintire , kindly checkout my PR **added resolution for linux distros #22**

**Comment by toddmcintire** [comment]
> @toddmcintire , kindly checkout my PR **added resolution for linux distros #22**

@gokul-srinath Thank you for the PR, Im going to give @bleakprestiger a few days to attempt their own solution since they kindly asked to be assigned this issue. If we don't hear from them here or within our community discord ill merge your PR.

**Comment by gokul-srinath** [comment]
> > @toddmcintire , kindly checkout my PR **added resolution for linux distros #22**
> 
> @gokul-srinath Thank you for the PR, Im going to give @bleakprestiger a few days to attempt their own solution since they kindly asked to be assigned this issue. If we don't hear from them here or within our community discord ill merge your PR.

makes sense, might as well work on other features/issues.

**Comment by toddmcintire** [comment]
@bleakprestiger any progress with this issue?

**Comment by toddmcintire** [comment]
Issue resolved with #22, Thank you for your amazing work @gokul-srinath
