### ISSUE TITLE
Get package count for linux distros

### ISSUE THREAD

**Issue by toddmcintire** [toddmcintire/jsfetch#3]
The ```packages(platform)``` function returns a number of currently installed packages on the system based on what is entered as the platform argument. 
Please create a ```if``` statement that when the ```platform``` is set to ```linux``` it will return the number of currently installed packages on a linux OS.

**Comment by JenieX** [comment]
I will be trying this one. 😄

**Comment by toddmcintire** [comment]
> I will be trying this one. 😄

Awesome, please do!😃

**Comment by ghost** [comment]
I'm new to Linux and I actually thought this issue wants you to list the NPM packages. :smile: 

Is this the command for it `apt list --installed`?

**Comment by toddmcintire** [comment]
Ah sorry, no I meant currently installed packages through the Linux distros package manager. 
```apt list --installed``` is correct for Debian based distros, the issue then becomes what if the user is using another distro like Arch Linux which does not use apt. 
This may be a issue that may need a more complex solution but until then we could just limit the use to Debian based systems until we can figure out what that complex solution may be.

**Comment by JenieX** [comment]
Awesome. It is supposed to return the number of installed packages only, right?

**Comment by toddmcintire** [comment]
Resolved by PR #18
